var num1 = 3;
var num2 = 10;
var c = "corolla";
var a1 = [1, 3, 5];
var a2 = [1, 2, 3];
console.log(c == 'corolla');
console.log(c == "civic");
console.log(c != "honda");
console.log(a1.length > a2.length);
console.log(a1.length == a2.length);
console.log(a1[1] == a2[2]);
console.log(num1 > num2);
console.log(num1 == num2);
console.log(num1 < num2);
console.log(num1 != num2);
