var p1 = "rawalpindi";
var p2 = "Chakwal";
var i12 = [0, 2, 4];
console.log(p1 == p2);
console.log(p1 != p2);
console.log("\n\n");
console.log(p1 == 'Rawalpindi');
console.log(p1 != 'Rawalpindi');
console.log("\n\n");
console.log(1 > 2);
console.log(1 < 2);
console.log(1 == 1);
console.log(2 != 2);
console.log(3 >= 3);
console.log(2 >= 323);
console.log(19 <= 20);
console.log(191 <= 20);
console.log("\n\n");
console.log(p1 != p2 && 2 > 1);
console.log(p1 == p2 && 2 <= 1);
console.log("\n\n");
console.log('Rawalpindi' != p1 || 1 >= 1);
console.log('Rawalpindi' != p1 || 0 >= 1);
console.log("\n\n");
console.log(i12[2] == 4);
console.log(i12[1] == 34);
